services:
  sportsstore:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver

  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "MyDatabaseSecret123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sportsstore-data:/var/opt/mssql   


volumes:
  sportsstore-data:
